### ISSUE TITLE
Dataset has 0 tokens

### ISSUE THREAD

**Issue by atl333** [NickBrisebois/DiscordChatAI-GPT2#7]
I get a "Dataset had 0 tokens" error

this is my chat.txt file in the master folder (./DiscordChatAI-GPT2-master/chat.txt) 
![image](https://user-images.githubusercontent.com/89211409/147713280-cb5da699-16f3-46ea-b260-a069a025a014.png)

Error:
```
PS D:\Users\repli\OneDrive\Documentos\GPT2 chatbot\ai pre trained models\training venv\DiscordChatAI-GPT2-master> C:/Python39/python.exe main.py --genmodel
2021-12-29 17:39:26.850267: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-29 17:39:27.714999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3965 MB memory:  
-> device: 0, name: NVIDIA GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5
models\355M
For larger models, the recommended finetune() parameters are:
        use_memory_saving_gradients = True  
        only_train_transformer_layers = True
        accumulate_gradients = 1

2021-12-29 17:39:38.742728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3965 MB memory:  
-> device: 0, name: NVIDIA GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5
Loading checkpoint models\355M\model.ckpt
Loading dataset...
0it [00:00, ?it/s]
dataset has 0 tokens
Training...
Traceback (most recent call last):
  File "D:\Users\repli\OneDrive\Documentos\GPT2 chatbot\ai pre trained models\training venv\DiscordChatAI-GPT2-master\main.py", line 44, in <module>
    main()
  File "D:\Users\repli\OneDrive\Documentos\GPT2 chatbot\ai pre trained models\training venv\DiscordChatAI-GPT2-master\main.py", line 35, in main
    ai.generate_models("355M", "./input.txt")
  File "D:\Users\repli\OneDrive\Documentos\GPT2 chatbot\ai pre trained models\training venv\DiscordChatAI-GPT2-master\Bot\ai.py", line 23, in generate_models
    gpt2.finetune(
  File "C:\Python39\lib\site-packages\gpt_2_simple\gpt_2.py", line 345, in finetune
    feed_dict={context: sample_batch()})
  File "C:\Python39\lib\site-packages\gpt_2_simple\gpt_2.py", line 312, in sample_batch
    return [data_sampler.sample(1024) for _ in range(batch_size)]
  File "C:\Python39\lib\site-packages\gpt_2_simple\gpt_2.py", line 312, in <listcomp>
    return [data_sampler.sample(1024) for _ in range(batch_size)]
  File "C:\Python39\lib\site-packages\gpt_2_simple\src\load_dataset.py", line 82, in sample
    assert length < self.total_size // len(
ZeroDivisionError: integer division or modulo by zero
```

Running it on VSCode, cuda 11.3, cuddn 8.2 iirc, python 3.9 

I tried renaming the text file from "chat" to "input" because of this line:

```
File "D:\Users\repli\OneDrive\Documentos\GPT2 chatbot\ai pre trained models\training venv\DiscordChatAI-GPT2-master\main.py", line 35, in main
    ai.generate_models("355M", "./input.txt")
```

and then I got an instant CUDA OOM error after like 2 seconds of running it, I have a mobile (laptop) RTX 2060, not the best, so what params should i change for it to run? I don't care if it takes 10 hours instead of 4 tbh, i just wanna be able to handle it with 4/6 GB of VRAM (I have 6 GB of VRAM but CUDA only can use 4 according to the powershell)

My data set consists of 30,000 messages, parsed from a politics channel and i appended repeated ones, so if someone sent 4 messages, they became one message, so the model doesn't think the person is replying to itself. (although idk if it is a good or bad idea) so in the end it has 20,000 lines after parsing to delete all links, messages with only links, messages starting with bot prefixes and all bot messages, so maybe it has around the content of 25,000 messages but with some lines being longer due to several messages being from the same person in a row

alternatively i assumed it could be possible that i skipped a part of the tokenizer process by renaming it to "input" so maybe my gpu can actually handle it and i just need to debug this

thanks a lot

**Comment by ONLYIN1** [comment]
having the same issue here
